#+STARTUP: overview hidestars logdone
#+COLUMNS: %38ITEM(Details) %7TODO(To Do) %TAGS(Context)
#+OPTIONS: tags:t timestamp:t todo:t TeX:t LaTeX:t
#+OPTIONS: @:t ::t |:t ^:t f:t
#+LANGUAGE: en
#+TITLE: Lignes Claires
[[https://opensource.org/licenses/BSD-3-Clause][https://img.shields.io/badge/License-BSD%203--Clause-blue.svg]]

[[https://github.com/arnaud-m/cryptator/actions/workflows/CryptatorTest.yml][file:https://github.com/arnaud-m/lignes-claires/actions/workflows/LignesClairesTest.yml/badge.svg]]

Lignes Claires is a solver for One-sided Crossing Minimization based on [[https://en.wikipedia.org/wiki/Constraint_programming][Constraint Programming]].\\
It is based on [[https://github.com/chocoteam/choco-solver][choco-solver]] which is an open-source Java library for Constraint Programming.

It will hopefully be a contestant of the [[https://pacechallenge.org/2024/][PACE Challenge 2024]].

* Download and Installation

  In the following, we distinguish two usages:
    - as a standalone application: the jar file includes all required dependencies,
    - as a library: the jar file excludes all dependencies.

** Prerequisites
  This project works on 32 bits and 64 bits environment and requires:

  - JDK 11+
  - Maven 3+

** As a stand-alone application

   This project uses the Cross-platform Maven build system.
   : mvn clean package
   or to skip unit tests
   : mvn clean package -DskipTests=true

   The jar file contains all required dependencies.
   The next step is simply to run the console application.
   : java -cp target/lignes-claires-*-with-dependencies.jar lignesclaires.LignesClaires

    Execute the main class without argument to display the help message.
** As a library

   The jar file does not contains any dependencies, as of being used as a dependency of another application.
   The next step is to add the jar file to your classpath of your application and also add the required dependencies.

*** Inside a maven project

    First, you must build from source and install it into your local .m2 repository.
    : mvn install

    Then, you only have to edit your pom.xml to declare the following library dependency:

 #+BEGIN_EXAMPLE
 <dependency>
    <groupId>fr.univ-cotedazur</groupId>
    <artifactId>lignes-claires</artifactId>
    <version>0.1.0-SNAPSHOT</version>
 </dependency>
 #+END_EXAMPLE

* Versioning

This project makes use of [[http://semver.org/][SemVer]] for versioning.
A list of existing versions can be found in the [[https://github.com/arnaud-m/cryptator/releases][project's releases]].

* Authors

See [[AUTHORS][AUTHORS]] and [[CONTRIBUTORS][CONTRIBUTORS]] files.

* License

This project is licensed under the [[https://opensource.org/licenses/BSD-3-Clause/][3-Clause BSD License]] - see the [[LICENSE][LICENSE]] file for details.
